* tickmarks TOC                                                    :TOC_5_gh:
 - [[#tickmarks][tickmarks]]
   - [[#introduction][Introduction]]
   - [[#contributing-to-tickmarks][Contributing to tickmarks]]
   - [[#copyright][Copyright]]

* tickmarks
** Introduction
   Tickmarks generates the "mathematical" structures for mediating tick marks,
   for, say, on a chart. Tickmarks does not generate the actual graphics -- we 
   leave that up to you. It just handles all the nuances for creating those tick 
   structures. You may use this in ways I cannot not anticipate.
   
   So let your imagination run wild. :)


** Contributing to tickmarks
 
   - Check out the latest master to make sure the feature hasn't been implemented or the bug hasn't been fixed yet.
   - Check out the issue tracker to make sure someone already hasn't requested it and/or contributed it.
   - Fork the project.
   - Start a feature/bugfix branch.
   - Commit and push until you are happy with your contribution.
   - Make sure to add tests for it. This is important so I don't break it in a future version unintentionally.
   - Please try not to mess with the Rakefile, version, or history. If you want to have your own version, or is otherwise necessary, that is fine, but please isolate to its own commit so I can cherry-pick around it.

** Copyright

   Copyright (c) 2017 Fred Mitchell. See LICENSE.txt for
   further details.
